# Generated by Django 3.0.7 on 2020-06-22 03:24

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('c++', 'C++'), ('python', 'Python'), ('qt', 'Qt-PyQt5'), ('git', 'GIT'), ('linux', 'Linux'), ('algorithms', 'Algorithms'), ('network', 'Network'), ('note', 'notes')], default=blog.models.Blog.category_default, max_length=15),
        ),
    ]
